CREATE TABLE IF NOT EXISTS SECURITIES.ZERODHA_MASTER_LIST (
	INSTRUMENT_TOKEN 	VARCHAR(15)		NOT NULL,
	EXCHANGE_TOKEN 		VARCHAR(10)		NOT NULL,
	TRADING_SYMBOL 		VARCHAR(100)	NOT NULL,
	SECURITY_NAME 		VARCHAR(100)	NULL,
	LAST_PRICE 			DECIMAL(10,4)	NOT NULL,
	EXPIRY				DATE			NULL,
	STRIKE_PRICE		DECIMAL(10,4)	NOT NULL,
	TICK_SIZE			DECIMAL(10,4)	NOT NULL,
	LOT_SIZE			INT				NOT NULL,
	INSTRUMENT_TYPE		VARCHAR(5)		NOT NULL,
	SEGMENT				VARCHAR(15)		NOT NULL,
	EXCHANGE			VARCHAR(3)		NOT NULL,
	INSERTION_TIMESTAMP	TIMESTAMPTZ		NOT NULL
);

SELECT CREATE_HYPERTABLE('SECURITIES.ZERODHA_MASTER_LIST','insertion_timestamp')

-- Report Github issue where if the column name is specified in capitals, it doesn't work.